### ISSUE TITLE
about AI progress

### ISSUE THREAD

**Issue by handsomekiwi** [Snarkie/YGOProAIScript#10]
Hi,I am a AI programmer . the tool I use is Windbot , link below:
https://github.com/IceYGO/windbot
Now AI work fine with link summon ,but it can't get information like category of monster,then I found here,could u give me some advise?thanks.

**Comment by Snarkie** [comment]
Hey kiwi,
sorry, I am afraid, I cannot help you. Windbot is entirely different compared to this project. I am not familiar with Windbot's API, I have no idea, how to get the information you need out of a card.

Try to find an API or documentation of any kind on Windbot. If there is none, Windbot seems to have some methods of getting informations from a card, like card.Id or card.Location, maybe try following the same pattern.

**Comment by handsomekiwi** [comment]
I have heard about the bad guy you met when you developing Ygopro2,I am sorry if he has caused you any uncomfortable,and the guy was kicked since 2017 .
And I want to tell u something about new AI
1.it can AI us AI now,can save lots of time
2AI is very smart now,you can try AI_Trickstar,it act like the real player,or new AI I wrote.
3.it support link summon
But it got less message,it can't read like IsImmuneToEffect,and it use YgoSharp server to get work,I saw YgoSharp in Ygopro2 ,maybe it has something similar with your's.
My future plan is move Windbot into Ygopro2,and improve Windbot.
Anyway thank's to reply me.XD

**Comment by Snarkie** [comment]
> I have heard about the bad guy you met when you developing Ygopro2,I am sorry if he has caused you any uncomfortable,and the guy was kicked since 2017 .

There seems to be some misinformation here. I never actively developed anything for YGOPro 2. I worked on the AI for YGOPro Percy, a couple other YGOPro versions (including YGOPro 2) then decided to adapt their respective clients to be able to use my script, with my permission of course. I do not recall having any trouble whatsoever with any of the YGOPro 2 devs.

>And I want to tell u something about new AI
1.it can AI us AI now,can save lots of time
2AI is very smart now,you can try AI_Trickstar,it act like the real player,or new AI I wrote.
3.it support link summon

Very nice to hear, that the AI is being improved. I will try it out at some point.

>My future plan is move Windbot into Ygopro2,and improve Windbot.

Best of luck to you :)

**Comment by handsomekiwi** [comment]
I think I got a wrong direction,I read ur opensource AI ,but I can't find how AI get [Duel.GetOperationInfo(i, CATEGORY_SPECIAL_SUMMON)] message from core,could u help me?

**Comment by handsomekiwi** [comment]
the place I read:
https://github.com/handsomekiwi/ygopro2/commit/270ec28b3d67d50372e07ffac87f98c24ea5ad59
