### ISSUE TITLE
ChainMaxxC Issue

### ISSUE THREAD

**Issue by neftalimich** [Snarkie/YGOProAIScript#7]
Hi Snarkie, i wanna contribute a little bit:
# Issue

function ChainMaxxC()
  for i=1,Duel.GetCurrentChain() do
    if Duel.GetOperationInfo(_~~**Duel.GetCurrentChain()**~~_, CATEGORY_SPECIAL_SUMMON) 
    and  Duel.GetChainInfo(_~~**Duel.GetCurrentChain()**~~_, CHAININFO_TRIGGERING_PLAYER)~=player_ai 
    then
      return true
    end
  end
  return false
end
# Fix

function ChainMaxxC()
  for **i=1**,Duel.GetCurrentChain() do
    if Duel.GetOperationInfo(**i**, CATEGORY_SPECIAL_SUMMON) 
    and  Duel.GetChainInfo(**i**, CHAININFO_TRIGGERING_PLAYER)~=player_ai 
    then
      return true
    end
  end
  return false
end

I guess this don't needs a "pull request" :)

**Comment by Snarkie** [comment]
fixed for next version
